language: csharp
sudo: false
dist: xenial
mono: none
dotnet: 2.1.4
group: deprecated-2017Q4

env:
	global:
	- DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_script:
  - dotnet restore ./VkNet.sln
script:
- dotnet test ./VkNet.Tests/VkNet.Tests.csproj -f netcoreapp2.0  --no-restore
